const express = require('express')
const router = express.Router()
const upload = require('../until/multer')
const appConstrollers = require('../constrollers/appConstrollers')
const accountConstrollers = require('../constrollers/accountConstrollers')
router.get('/login',accountConstrollers.show_login)
router.get('/register',accountConstrollers.show_register)
router.post('/login',accountConstrollers.login)
router.post('/register',accountConstrollers.sign_in)
//router.post('/search',accountConstrollers.search)

router.get('/',appConstrollers.index)
router.get('/logout',appConstrollers.logout)
router.get('/sent',appConstrollers.show_sent)
router.get('/detail/:id',appConstrollers.show_detail)
router.get('/account-detail/:id',appConstrollers.show_account)
router.get('/:slug',appConstrollers.show_404)
router.post('/action', appConstrollers.action)
router.post(['/','/sent'],appConstrollers.output)
router.delete('/kill/:id',appConstrollers.kill)
router.delete('/delete/:id',appConstrollers.delete)
router.put('/account-detail/:id',upload.single('image'),appConstrollers.update_account)

module.exports = router